<template>
  <div class="space-y-6">
    <!-- Main Two-Column Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <!-- LEFT PANEL: SUBTITLE DOWNLOADER -->
      <div
        class="p-6 rounded-2xl border space-y-5 shadow-sm flex flex-col justify-between"
        style="background-color: var(--bg-surface); border-color: var(--border-subtle);"
      >
        <div class="space-y-4">
          <h2 class="text-xs font-bold uppercase tracking-wider flex items-center gap-2" style="color: var(--text-primary);">
            <span>📥</span>
            <span>{{ t.downloadTitle }}</span>
          </h2>

          <!-- Video URL input -->
          <div class="space-y-1.5">
            <label class="block text-[11px] font-semibold" style="color: var(--text-secondary);">
              {{ t.urlLabel }}
            </label>
            <input
              v-model="downloadUrl"
              type="text"
              :placeholder="t.urlPlaceholder"
              class="w-full px-4 py-2.5 rounded-xl text-xs border outline-none font-mono"
              style="background-color: var(--bg-input); border-color: var(--border-subtle); color: var(--text-primary);"
            />
          </div>

          <!-- Language checkboxes -->
          <div class="space-y-2">
            <label class="block text-[11px] font-semibold" style="color: var(--text-secondary);">
              {{ t.languagesLabel }}
            </label>
            <div class="grid grid-cols-2 sm:grid-cols-3 gap-2">
              <label
                v-for="lang in availableLangs"
                :key="lang.code"
                class="flex items-center gap-2 text-xs cursor-pointer p-2 rounded-lg border transition"
                :style="{
                  backgroundColor: selectedLangs.includes(lang.code) ? 'var(--bg-card)' : 'transparent',
                  borderColor: selectedLangs.includes(lang.code) ? 'var(--border-brass)' : 'var(--border-subtle)',
                  color: selectedLangs.includes(lang.code) ? 'var(--accent-brass)' : 'var(--text-secondary)'
                }"
              >
                <input
                  type="checkbox"
                  :value="lang.code"
                  v-model="selectedLangs"
                  class="rounded cursor-pointer"
                />
                <span class="font-medium">{{ lang.name }}</span>
                <span class="text-[10px] font-mono opacity-70">({{ lang.code }})</span>
              </label>
            </div>
          </div>

          <!-- Auto-generated subtitles checkbox -->
          <div class="flex items-center gap-2 pt-1">
            <input type="checkbox" v-model="includeAutoGenerated" id="chk-auto-sub" class="rounded cursor-pointer" />
            <label for="chk-auto-sub" class="text-xs cursor-pointer" style="color: var(--text-secondary);">
              {{ t.autoGeneratedLabel }}
            </label>
          </div>

          <!-- Output Directory -->
          <div class="space-y-1.5 pt-2">
            <label class="block text-[11px] font-semibold" style="color: var(--text-secondary);">
              {{ t.outputFolderLabel }}
            </label>
            <div class="flex gap-2">
              <input
                v-model="downloadOutputDir"
                type="text"
                placeholder="Default Downloads"
                class="flex-1 px-4 py-2 rounded-xl text-xs border outline-none font-mono"
                style="background-color: var(--bg-input); border-color: var(--border-subtle); color: var(--text-primary);"
              />
              <button
                @click="browseDownloadDir"
                class="px-3 py-2 rounded-xl border text-xs font-semibold cursor-pointer"
                style="background-color: var(--bg-card); border-color: var(--border-subtle);"
              >
                📁
              </button>
            </div>
          </div>
        </div>

        <div class="pt-4 border-t" style="border-color: var(--border-subtle);">
          <button
            @click="downloadSubtitles"
            :disabled="!downloadUrl || downloading"
            class="w-full py-2.5 font-bold text-xs rounded-xl shadow-lg transition flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
            style="background-color: var(--accent-brass); color: var(--bg-primary);"
          >
            <span>📥</span>
            <span>{{ downloading ? t.downloading : t.downloadBtn }}</span>
          </button>
        </div>
      </div>

      <!-- RIGHT PANEL: SUBTITLE PROCESSOR & EMBEDDER -->
      <div
        class="p-6 rounded-2xl border space-y-5 shadow-sm flex flex-col justify-between"
        style="background-color: var(--bg-surface); border-color: var(--border-subtle);"
      >
        <div class="space-y-4">
          <h2 class="text-xs font-bold uppercase tracking-wider flex items-center gap-2" style="color: var(--text-primary);">
            <span>⚙️</span>
            <span>{{ t.processTitle }}</span>
          </h2>

          <!-- Subtitle File Selector (DND + Browse) -->
          <div class="space-y-1.5">
            <label class="block text-[11px] font-semibold" style="color: var(--text-secondary);">
              {{ t.subtitleFileLabel }}
            </label>
            <div class="flex gap-2">
              <input
                v-model="subtitlePath"
                type="text"
                :placeholder="t.selectSubtitlePlaceholder"
                class="flex-1 px-4 py-2.5 rounded-xl text-xs border outline-none font-mono"
                style="background-color: var(--bg-input); border-color: var(--border-subtle); color: var(--text-primary);"
              />
              <button
                @click="browseSubtitleFile"
                class="px-3.5 py-2 rounded-xl border text-xs font-semibold hover:opacity-90 cursor-pointer"
                style="background-color: var(--bg-card); color: var(--text-primary); border-color: var(--border-subtle);"
              >
                📁
              </button>
            </div>
          </div>

          <!-- Video File Selector (DND + Browse) -->
          <div class="space-y-1.5">
            <label class="block text-[11px] font-semibold" style="color: var(--text-secondary);">
              {{ t.videoFileLabel }}
            </label>
            <div class="flex gap-2">
              <input
                v-model="videoPath"
                type="text"
                :placeholder="t.selectVideoPlaceholder"
                class="flex-1 px-4 py-2.5 rounded-xl text-xs border outline-none font-mono"
                style="background-color: var(--bg-input); border-color: var(--border-subtle); color: var(--text-primary);"
              />
              <button
                @click="browseVideoFile"
                class="px-3.5 py-2 rounded-xl border text-xs font-semibold hover:opacity-90 cursor-pointer"
                style="background-color: var(--bg-card); color: var(--text-primary); border-color: var(--border-subtle);"
              >
                📁
              </button>
            </div>
          </div>

          <!-- Subtitle Format Conversion -->
          <div class="p-3.5 rounded-xl border space-y-2" style="background-color: var(--bg-input); border-color: var(--border-subtle);">
            <label class="block text-[11px] font-semibold" style="color: var(--text-secondary);">
              {{ t.convertFormatLabel }}
            </label>
            <div class="flex gap-2">
              <select
                v-model="targetSubFormat"
                class="flex-1 rounded-lg px-3 py-1.5 text-xs border outline-none font-mono"
                style="background-color: var(--bg-card); border-color: var(--border-subtle); color: var(--text-primary);"
              >
                <option value="srt">SRT (SubRip - Universal)</option>
                <option value="vtt">VTT (WebVTT - HTML5/Web)</option>
                <option value="ass">ASS (Advanced SubStation)</option>
                <option value="ssa">SSA (SubStation Alpha)</option>
              </select>
              <button
                @click="convertFormat"
                :disabled="!subtitlePath || isProcessing"
                class="px-4 py-1.5 text-xs font-bold rounded-lg border transition hover:opacity-90 cursor-pointer disabled:opacity-50"
                style="background-color: var(--bg-card); color: var(--accent-brass); border-color: var(--border-brass);"
              >
                {{ t.convertBtn }}
              </button>
            </div>
          </div>

          <!-- Timing Shift Adjuster -->
          <div class="p-3.5 rounded-xl border space-y-2" style="background-color: var(--bg-input); border-color: var(--border-subtle);">
            <div class="flex items-center justify-between text-[11px]">
              <span class="font-semibold" style="color: var(--text-secondary);">{{ t.timingShiftLabel }}</span>
              <span class="font-mono font-bold" style="color: var(--accent-brass);">
                {{ shiftSeconds >= 0 ? `+${shiftSeconds.toFixed(1)}s` : `${shiftSeconds.toFixed(1)}s` }}
              </span>
            </div>
            <div class="flex items-center gap-3">
              <input
                v-model.number="shiftSeconds"
                type="range"
                min="-10.0"
                max="10.0"
                step="0.1"
                class="flex-1 cursor-pointer"
              />
              <button
                @click="adjustTiming"
                :disabled="!subtitlePath || isProcessing || shiftSeconds === 0"
                class="px-4 py-1.5 text-xs font-bold rounded-lg border transition hover:opacity-90 cursor-pointer disabled:opacity-50"
                style="background-color: var(--bg-card); color: var(--text-primary); border-color: var(--border-subtle);"
              >
                {{ t.applyShiftBtn }}
              </button>
            </div>
          </div>
        </div>

        <!-- Embedding Actions -->
        <div class="grid grid-cols-2 gap-3 pt-3 border-t" style="border-color: var(--border-subtle);">
          <button
            @click="embedSubtitles('mux')"
            :disabled="!videoPath || !subtitlePath || isProcessing"
            class="py-2.5 text-xs font-bold rounded-xl border transition flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50 hover:opacity-90"
            style="background-color: var(--bg-card); color: var(--text-primary); border-color: var(--border-subtle);"
          >
            <span>📎</span>
            <span>{{ t.softSubBtn }}</span>
          </button>

          <button
            @click="embedSubtitles('burn')"
            :disabled="!videoPath || !subtitlePath || isProcessing"
            class="py-2.5 text-xs font-bold rounded-xl shadow-lg transition flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
            style="background-color: var(--accent-brass); color: var(--bg-primary);"
          >
            <span>🔥</span>
            <span>{{ t.hardSubBtn }}</span>
          </button>
        </div>
      </div>
    </div>

    <!-- Execution Log Box -->
    <div v-if="logLines.length > 0" class="p-5 rounded-2xl border space-y-2 shadow-sm" style="background-color: var(--bg-surface); border-color: var(--border-subtle);">
      <label class="block text-xs font-bold uppercase tracking-wider" style="color: var(--text-muted);">
        {{ t.processLog }}
      </label>
      <div
        class="p-4 rounded-xl font-mono text-[11px] max-h-36 overflow-y-auto space-y-1"
        style="background-color: var(--bg-card); border: 1px solid var(--border-subtle); color: var(--text-secondary);"
      >
        <div v-for="(line, idx) in logLines" :key="idx" class="truncate">
          {{ line }}
        </div>
      </div>
    </div>

    <!-- Error Panel Integration -->
    <ErrorPanel
      v-if="errorInfo"
      :title="errorInfo.title"
      :message="errorInfo.message"
      :traceback="errorInfo.traceback"
      @retry="retryLastAction"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useToastStore } from '../stores/toastStore'
import { apiClient } from '../services/apiClient'
import ErrorPanel from './ErrorPanel.vue'

const toastStore = useToastStore()

const t = {
  downloadTitle: 'Download Subtitles from Online Video',
  urlLabel: 'Source Video / Media URL',
  urlPlaceholder: 'Paste YouTube or online video link...',
  languagesLabel: 'Subtitle Language Tracks',
  autoGeneratedLabel: 'Include Auto-Generated / ASR Subtitles',
  outputFolderLabel: 'Destination Directory',
  downloadBtn: 'Download Subtitle Tracks',
  downloading: 'Downloading Subtitles...',
  processTitle: 'Subtitle Processing & Video Embedding',
  subtitleFileLabel: 'Subtitle File (SRT, VTT, ASS, SSA)',
  selectSubtitlePlaceholder: 'Select subtitle file...',
  videoFileLabel: 'Target Video File (for Soft/Hard Subtitles)',
  selectVideoPlaceholder: 'Select target video file...',
  convertFormatLabel: 'Convert Subtitle Format',
  convertBtn: 'Convert Format',
  timingShiftLabel: 'Timing Offset / Synchronization Shift',
  applyShiftBtn: 'Adjust Sync',
  softSubBtn: 'Soft Subtitle (Mux Track)',
  hardSubBtn: 'Hard Subtitle (Burn-in Video)',
  processLog: 'Subtitle Process Log'
}

const availableLangs = [
  { code: 'tr', name: 'Turkish' },
  { code: 'en', name: 'English' },
  { code: 'de', name: 'German' },
  { code: 'fr', name: 'French' },
  { code: 'es', name: 'Spanish' }
]

const downloadUrl = ref('')
const selectedLangs = ref<string[]>(['tr', 'en'])
const includeAutoGenerated = ref(true)
const downloadOutputDir = ref('')
const downloading = ref(false)

const subtitlePath = ref('')
const videoPath = ref('')
const targetSubFormat = ref('srt')
const shiftSeconds = ref(0.0)
const isProcessing = ref(false)

const logLines = ref<string[]>([])
const errorInfo = ref<{ title: string; message: string; traceback?: string } | null>(null)
let lastAction: (() => Promise<void>) | null = null

async function browseDownloadDir() {
  try {
    const { open } = await import('@tauri-apps/plugin-dialog')
    const selected = await open({ directory: true, multiple: false })
    if (selected && typeof selected === 'string') {
      downloadOutputDir.value = selected
    }
  } catch {
    toastStore.info('Enter destination directory directly.')
  }
}

async function browseSubtitleFile() {
  try {
    const { open } = await import('@tauri-apps/plugin-dialog')
    const selected = await open({
      multiple: false,
      filters: [{ name: 'Subtitle Files', extensions: ['srt', 'vtt', 'ass', 'ssa', 'sub'] }]
    })
    if (selected && typeof selected === 'string') {
      subtitlePath.value = selected
      toastStore.success(`Selected subtitle: ${selected}`)
    }
  } catch {
    toastStore.info('Enter subtitle path directly.')
  }
}

async function browseVideoFile() {
  try {
    const { open } = await import('@tauri-apps/plugin-dialog')
    const selected = await open({
      multiple: false,
      filters: [{ name: 'Video Files', extensions: ['mp4', 'mkv', 'avi', 'mov', 'webm'] }]
    })
    if (selected && typeof selected === 'string') {
      videoPath.value = selected
      toastStore.success(`Selected video: ${selected}`)
    }
  } catch {
    toastStore.info('Enter video path directly.')
  }
}

async function downloadSubtitles() {
  if (!downloadUrl.value.trim()) return
  downloading.value = true
  errorInfo.value = null
  lastAction = downloadSubtitles
  logLines.value.push(`[${new Date().toLocaleTimeString()}] Fetching subtitles for: ${downloadUrl.value}`)

  try {
    const res = await apiClient.downloadSubtitles({
      url: downloadUrl.value.trim(),
      output_dir: downloadOutputDir.value.trim() || undefined,
      languages: selectedLangs.value,
      auto_generated: includeAutoGenerated.value
    })
    logLines.value.push(`[${new Date().toLocaleTimeString()}] Subtitle task enqueued: ID ${res.task_id}`)
    toastStore.success(`Subtitle download task queued`)
    downloadUrl.value = ''
  } catch (e: any) {
    errorInfo.value = {
      title: 'Subtitle Download Failed',
      message: e.message || 'Could not fetch subtitle streams.',
      traceback: String(e)
    }
    toastStore.error('Subtitle download failed')
  } finally {
    downloading.value = false
  }
}

async function convertFormat() {
  if (!subtitlePath.value.trim()) return
  isProcessing.value = true
  errorInfo.value = null
  lastAction = convertFormat

  try {
    const res = await apiClient.processSubtitles({
      action: 'convert',
      subtitle_file: subtitlePath.value.trim(),
      output_format: targetSubFormat.value
    })
    logLines.value.push(`[${new Date().toLocaleTimeString()}] Converted subtitle saved: ${res.output_file}`)
    toastStore.success(`Converted to ${targetSubFormat.value.toUpperCase()}`)
  } catch (e: any) {
    errorInfo.value = {
      title: 'Subtitle Format Conversion Failed',
      message: e.message || 'Could not convert subtitle format.',
      traceback: String(e)
    }
    toastStore.error('Conversion failed')
  } finally {
    isProcessing.value = false
  }
}

async function adjustTiming() {
  if (!subtitlePath.value.trim()) return
  isProcessing.value = true
  errorInfo.value = null
  lastAction = adjustTiming

  try {
    const res = await apiClient.processSubtitles({
      action: 'shift',
      subtitle_file: subtitlePath.value.trim(),
      shift_seconds: shiftSeconds.value
    })
    logLines.value.push(`[${new Date().toLocaleTimeString()}] Adjusted timing (${shiftSeconds.value}s) saved: ${res.output_file}`)
    toastStore.success(`Subtitle sync adjusted by ${shiftSeconds.value}s`)
  } catch (e: any) {
    errorInfo.value = {
      title: 'Timing Shift Failed',
      message: e.message || 'Could not shift subtitle timestamps.',
      traceback: String(e)
    }
    toastStore.error('Timing adjustment failed')
  } finally {
    isProcessing.value = false
  }
}

async function embedSubtitles(mode: 'mux' | 'burn') {
  if (!videoPath.value.trim() || !subtitlePath.value.trim()) return
  isProcessing.value = true
  errorInfo.value = null
  lastAction = () => embedSubtitles(mode)
  logLines.value.push(`[${new Date().toLocaleTimeString()}] Starting ${mode === 'mux' ? 'soft subtitle muxing' : 'hard subtitle burning'}...`)

  try {
    const res = await apiClient.processSubtitles({
      action: mode,
      video_file: videoPath.value.trim(),
      subtitle_file: subtitlePath.value.trim()
    })
    logLines.value.push(`[${new Date().toLocaleTimeString()}] Embedded video created: ${res.output_file}`)
    toastStore.success(mode === 'mux' ? 'Soft subtitles embedded' : 'Hard subtitles burned into video')
  } catch (e: any) {
    errorInfo.value = {
      title: `Subtitle ${mode === 'mux' ? 'Mux' : 'Burn'} Failed`,
      message: e.message || 'Could not embed subtitles into video stream.',
      traceback: String(e)
    }
    toastStore.error('Subtitle embedding failed')
  } finally {
    isProcessing.value = false
  }
}

function retryLastAction() {
  if (lastAction) {
    lastAction()
  }
}
</script>
